import {test} from 'node:test';
import assert from 'node:assert/strict';
import {FrameWriter} from '../core.mjs';
test('queue fails closed on overflow and retains attempted take evidence',async()=>{let release;const w=new FrameWriter('/unused',{maxFrames:1,write:()=>new Promise(r=>release=r)});assert.equal(w.push(Buffer.alloc(2),{file:'a'}),true);assert.equal(w.push(Buffer.alloc(2),{file:'b'}),false);release();await assert.rejects(w.drain(),/overflow/);assert.equal(w.rows.length,1);});
test('disk failure invalidates recording',async()=>{const w=new FrameWriter('/unused',{write:async()=>{throw Error('disk full')}});w.push(Buffer.alloc(1),{file:'a'});await assert.rejects(w.drain(),/disk full/);assert.equal(w.rows[0].writeError,'disk full');});
test('queue records writes, sizes, hashes, completion and stays bounded',async()=>{const w=new FrameWriter('/unused',{write:async()=>{}});for(let i=0;i<20;i++)w.push(Buffer.from('jpeg'),{file:String(i)});await w.drain();assert.equal(w.bytes,0);assert.ok(w.peakBytes<=w.maxBytes);assert.ok(w.rows.every(r=>r.sha256.length===64&&r.writeCompletedEpochMs&&r.bytes===4));});
import {frameSchedule} from '../timing.mjs';
test('elapsed-time mapping keeps a native stall and preserves chapter length',()=>{const frames=[{timestamp:10},{timestamp:10.02},{timestamp:10.5},{timestamp:11}];const map=frameSchedule(frames,10,1);assert.equal(map.length,30);assert.equal(map[14].sourceIndex,1);assert.equal(map[15].sourceIndex,2);assert.equal(map[29].sourceIndex,2);});
test('out-of-order CDP delivery is encoded by original timestamp, retaining source identity',()=>{const frames=[{timestamp:10},{timestamp:10.1},{timestamp:10.05},{timestamp:10.15}];const map=frameSchedule(frames,10,.2);assert.equal(map[2].sourceIndex,2);assert.equal(map[3].sourceIndex,1);assert.equal(map[5].sourceIndex,3);});
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {chooseTake} from '../assemble.mjs';
test('a successful capture with missing native actions cannot be selected',async()=>{const out=await mkdtemp(path.join(os.tmpdir(),'comparison-control-gate-'));try{const dir=path.join(out,'rehearsal','site','ball','take-1');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'capture.json'),JSON.stringify({errors:[],frames:[]}));await writeFile(path.join(dir,'receipts.json'),JSON.stringify({errors:[],events:[]}));await assert.rejects(chooseTake(out,'rehearsal',{id:'site'},{id:'ball',durationSeconds:18}),/No technically valid/);}finally{await rm(out,{recursive:true});}});

import {classifyGaps} from '../timing.mjs';
test('gap attribution compares full native intervals including their late closing receipt',()=>{const f=[0,.016,.032,.251,.268,.285].map(t=>({timestamp:100+t}));const r={frames:[{epoch:100058.7,now:58.7,receipt:59.8},{epoch:100242,now:242,receipt:248,rawDelta:183.3}]};const g=classifyGaps(f,r,{start:100,duration:1,offset:0,uncertainty:.02});assert.equal(g[0].classification,'native-animation-stall');assert.equal(g[0].affectsFilm,true);});
test('short or unrelated native stalls cannot excuse longer missing capture intervals',()=>{const f=[0,.016,.032,.4,.416].map(t=>({timestamp:100+t}));for(const r of [{epoch:100350,rawDelta:90},{epoch:100950,rawDelta:350}])assert.equal(classifyGaps(f,{frames:[{epoch:r.epoch-r.rawDelta,now:r.epoch-r.rawDelta-100000,receipt:r.epoch-r.rawDelta-100000},{...r,now:r.epoch-100000,receipt:r.epoch-100000}]},{start:100,duration:1,offset:0,uncertainty:.017})[0].classification,'unexplained');});
test('post-roll gaps stay in evidence while any gap intersecting the film still counts',()=>{const f=[0,.016,.032,.25,.267,.5,.517].map(t=>({timestamp:100+t}));const g=classifyGaps(f,{frames:[]},{start:100.25,duration:.1,offset:0,uncertainty:.017});assert.equal(g[0].affectsFilm,false);assert.equal(g[1].affectsFilm,true);assert.ok(g.every(x=>x.classification==='unexplained'));});

test('independent rejection vectors remain unexplained with complete callback evidence',()=>{for(const [times,native] of [[[0,.016,.032,.244,.26,.276],[[48,16],[64,16],[80,16],[92,12],[275,183]]],[[0,.09,.18,.68,.77,.86],[[270,16],[350,16],[370,20],[650,280]]]]){const frames=times.map(t=>({timestamp:100+t})),receipt={frames:native.map(([now,rawDelta])=>({epoch:100000+now,now,receipt:now,rawDelta}))};assert.equal(classifyGaps(frames,receipt,{start:100,duration:1,clockUncertainty:.001})[0].classification,'unexplained');}});
test('probe uncertainty consumes the fixed frame budget rather than loosening it',()=>{const frames=[100,100.016,100.032,100.251,100.268],receipt={frames:[{epoch:100058.7,now:58.7,receipt:59.8},{epoch:100242,now:242,receipt:248,rawDelta:183.3}]};assert.equal(classifyGaps(frames.map(timestamp=>({timestamp})),receipt,{start:100,duration:1,clockUncertainty:.01})[0].classification,'unexplained');});

import {clockAlignment} from '../timing.mjs';
test('a pause between clock reads cannot create a false precise epoch offset',()=>{const clocks=Array.from({length:6},(_,i)=>({phase:i<3?'before':'after',hostBeforeEpochMs:100000,hostAfterEpochMs:100101,pageWallBeforeEpochMs:100000,pageEpochMs:100000.5,pageWallAfterEpochMs:100100}));const r=clockAlignment(clocks);assert.equal(r.passed,false);assert.ok(r.bracket[0]<=0&&r.bracket[1]>=0);});
test('short bracketed epoch probes validate while a wall-clock jump invalidates alignment',()=>{const clocks=Array.from({length:6},(_,i)=>({phase:i<3?'before':'after',hostBeforeEpochMs:100000,hostAfterEpochMs:100002,pageWallBeforeEpochMs:100001,pageEpochMs:100001.5,pageWallAfterEpochMs:100001}));assert.equal(clockAlignment(clocks).passed,true);for(const c of clocks.slice(3)){c.hostBeforeEpochMs+=100;c.hostAfterEpochMs+=100;c.pageWallBeforeEpochMs+=100;c.pageWallAfterEpochMs+=100;}assert.equal(clockAlignment(clocks).passed,false);});
