import {mkdir,readdir,writeFile,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {run,json,save,cmd} from './core.mjs';
import {inspectTiming,frameSchedule} from './timing.mjs';
const font='/System/Library/Fonts/Supplemental/Arial.ttf';
const chapterNames=['CITY OVERVIEW','ONE BANK SWING','CHARGES · SLOW MOTION · REWIND'];
export async function chooseTake(out,kind,b,chapter){const parent=path.join(out,kind,b.id,chapter.id);const names=(await readdir(parent)).filter(n=>n.startsWith('take-')).sort();for(const name of names){const dir=path.join(parent,name);let c,r;try{c=await json(path.join(dir,'capture.json'));r=await json(path.join(dir,'receipts.json'));}catch{continue;}if(c.error||c.errors.length||r.errors.length)continue;const timing=await inspectTiming(dir,chapter.durationSeconds);if(timing.passed)return {dir,c,r,timing};}throw Error(`No technically valid ${kind} take for ${b.id}/${chapter.id}`);}
export default async function assemble({out,builds,scenario,args=[]}){const kind=args.includes('--rehearsal')?'rehearsal':'official';const deliver=path.join(out,kind==='official'?'delivery':'rehearsal-delivery');await mkdir(deliver,{recursive:true});const masters=[];const selection=[];
 for(const b of builds){const chapters=[];for(const chapter of scenario.chapters){const take=await chooseTake(out,kind,b,chapter);selection.push({build:b.id,chapter:chapter.id,take:path.relative(out,take.dir)});const map=frameSchedule(take.c.frames,take.timing.start,chapter.durationSeconds);const list=path.join(take.dir,'encode.ffconcat');let content='ffconcat version 1.0\n';// Exact output frame map: repeat source JPEGs for visible holds; never interpolate.
 for(const row of map)content+=`file '${path.join(take.dir,'frames',take.c.frames[row.sourceIndex].file)}'\noption framerate 30\nduration 0.033333333333\n`;await writeFile(list,content);const film=path.join(take.dir,'clean.mp4');await run('ffmpeg',['-v','error','-n','-f','concat','-safe','0','-i',list,'-an','-frames:v',String(map.length),'-r','30','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',film]);chapters.push(film);}
 const list=path.join(deliver,`${b.id}-chapters.txt`);await writeFile(list,chapters.map(p=>`file '${p}'`).join('\n'));const clean=path.join(deliver,`${b.folder}-clean.mp4`);await run('ffmpeg',['-v','error','-n','-f','concat','-safe','0','-i',list,'-c','copy','-movflags','+faststart',clean]);masters.push(clean);
 const title=`drawtext=fontfile='${font}':text='${b.label}':x=64:y=21:fontsize=28:fontcolor=white`;
 const captions=chapterNames.map((name,i)=>`drawtext=fontfile='${font}':text='${name}':x=w-tw-64:y=23:fontsize=24:fontcolor=0x9dada9:enable='gte(t,${scenario.chapters[i].startSeconds})*lt(t,${scenario.chapters[i].startSeconds+scenario.chapters[i].durationSeconds})'`).join(',');
 await run('ffmpeg',['-v','error','-n','-i',clean,'-vf',`scale=1792:1008,pad=1920:1080:64:72:color=0x111a1b,${title},${captions}`,'-an','-frames:v','2100','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',path.join(deliver,`${b.folder}.mp4`)]);
 }
 if(builds.length===3){const filters=masters.map((_,i)=>`[${i}:v]scale=1280:720[v${i}]`).join(';')+';[v0][v1][v2]hstack=inputs=3,pad=3840:840:0:120:color=0x111a1b,'+builds.map((b,i)=>`drawtext=fontfile='${font}':text='${b.label}':x=${i*1280+36}:y=24:fontsize=34:fontcolor=white`).join(',')+','+chapterNames.map((name,i)=>`drawtext=fontfile='${font}':text='${name} · same native actions / elapsed time':x=36:y=78:fontsize=24:fontcolor=0x9dada9:enable='gte(t,${scenario.chapters[i].startSeconds})*lt(t,${scenario.chapters[i].startSeconds+scenario.chapters[i].durationSeconds})'`).join(',');await run('ffmpeg',['-v','error','-n',...masters.flatMap(p=>['-i',p]),'-filter_complex',filters,'-an','-frames:v','2100','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',path.join(deliver,'demolition-comparison.mp4')]);}
 await save(path.join(deliver,'selection.json'),selection);console.log(`Assembled ${kind} films: ${deliver}`);
}
