import {mkdir,readdir,writeFile,copyFile,readFile,rename} from 'node:fs/promises';
import path from 'node:path';
import {run,json,save,cmd,hash,demo} from './core.mjs';
import {validateActions} from './control-checks.mjs';
import {fingerprint} from './verify.mjs';
import {inspectTiming,frameSchedule} from './timing.mjs';
const font='/System/Library/Fonts/Supplemental/Arial.ttf';
const chapterNames=['CITY OVERVIEW','ONE BANK SWING','CHARGES · SLOW MOTION · REWIND'];
const nativeCaption=(b,i)=>i<2?chapterNames[i]:b.id==='site'?'3 AUTO CHARGES · SLOW · AUTO REWIND':b.id==='sol'?'3 MANUAL CHARGES · SLOW · HELD REWIND':'3 MANUAL CHARGES · SLOW · TOGGLE REWIND';
export async function chooseTake(out,kind,b,chapter,expectedFingerprint=null){if(kind==='official'&&!expectedFingerprint)expectedFingerprint=(await json(path.join(out,'freeze.json'))).sha256;const parent=path.join(out,kind,b.id,chapter.id);const names=(await readdir(parent)).filter(n=>n.startsWith('take-')).sort();for(const name of names){const dir=path.join(parent,name);let c,r;try{c=await json(path.join(dir,'capture.json'));r=await json(path.join(dir,'receipts.json'));}catch{continue;}if(c.error||c.errors.length||r.errors.length)continue;if(expectedFingerprint){const inputs=await json(path.join(dir,'inputs.json'));if(inputs.sha256!==expectedFingerprint)continue;}try{const controls=validateActions(b,chapter,r);await save(path.join(dir,'controls.json'),controls);}catch(error){await save(path.join(dir,'controls.json'),{passed:false,error:error.message});continue;}const inspectionKey=hash(JSON.stringify({capture:hash(await readFile(path.join(dir,'capture.json'))),receipts:hash(await readFile(path.join(dir,'receipts.json'))),analyzer:hash(await readFile(path.join(demo,'timing.mjs'))),duration:chapter.durationSeconds}));let timing;try{const cached=await json(path.join(dir,'timing-cache.json'));if(cached.inspectionKey===inspectionKey&&cached.resultSha256===hash(await readFile(path.join(dir,'timing.json'))))timing=await json(path.join(dir,'timing.json'));}catch{}if(!timing){timing=await inspectTiming(dir,chapter.durationSeconds);await save(path.join(dir,'timing-cache.json'),{inspectionKey,resultSha256:hash(await readFile(path.join(dir,'timing.json')))});}if(timing.passed)return {dir,c,r,timing};}throw Error(`No technically valid ${kind} take for ${b.id}/${chapter.id}`);}
async function encode(args,file,identity){const signature=hash(JSON.stringify({args,identity}));try{const prior=await json(file+'.encoding.json');if(prior.signature!==signature||prior.sha256!==hash(await readFile(file)))throw Error(`Existing encoding does not match current inputs: ${file}`);return;}catch(e){if(e.code!=='ENOENT')throw e;}try{await readFile(file);throw Error(`Unverified existing encoding retained: ${file}`);}catch(e){if(e.code!=='ENOENT')throw e;}const temporary=file.replace(/\.mp4$/,`.partial-${Date.now()}.mp4`);await run('ffmpeg',[...args,temporary]);await rename(temporary,file);await save(file+'.encoding.json',{signature,sha256:hash(await readFile(file)),identity,args});}
export default async function assemble({out,builds,scenario,args=[]}){const kind=args.includes('--rehearsal')?'rehearsal':'official';const deliver=path.join(out,kind==='official'?'delivery':'rehearsal-delivery');await mkdir(deliver,{recursive:true});const masters=[];const selection=[];const delays=[];
 for(const b of builds){const chapters=[];for(const chapter of scenario.chapters){const take=await chooseTake(out,kind,b,chapter);if(kind==='official'){let checked=0;for(const f of take.c.frames){if(hash(await readFile(path.join(take.dir,'frames',f.file)))!==f.sha256)throw Error(`Source JPEG hash mismatch: ${take.dir}/${f.file}`);checked++;}await save(path.join(take.dir,'source-frame-verification.json'),{passed:true,checked,algorithm:'sha256'});}selection.push({build:b.id,chapter:chapter.id,take:path.relative(out,take.dir)});delays.push(...take.timing.actionDelays.map(d=>({...d,build:b.id,filmTime:chapter.startSeconds+d.actual})));const map=frameSchedule(take.c.frames,take.timing.start,chapter.durationSeconds);const list=path.join(take.dir,'encode.ffconcat');let content='ffconcat version 1.0\n';// Exact output frame map: repeat source JPEGs for visible holds; never interpolate.
 for(const row of map)content+=`file '${path.join(take.dir,'frames',take.c.frames[row.sourceIndex].file)}'\noption framerate 30\nduration 0.033333333333\n`;await writeFile(list,content);const film=path.join(take.dir,'clean.mp4');await encode(['-v','error','-n','-f','concat','-safe','0','-i',list,'-an','-frames:v',String(map.length),'-r','30','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart'],film,{map,sourceHashes:take.c.frames.map(f=>f.sha256)});chapters.push(film);}
 const list=path.join(deliver,`${b.id}-chapters.txt`);await writeFile(list,chapters.map(p=>`file '${p}'`).join('\n'));const clean=path.join(deliver,`${b.folder}-clean.mp4`);await encode(['-v','error','-n','-f','concat','-safe','0','-i',list,'-c','copy','-movflags','+faststart'],clean,{chapters:await Promise.all(chapters.map(async f=>hash(await readFile(f))))});masters.push(clean);
 const delayAnnotations=delays.filter(d=>d.build===b.id).map(d=>`drawtext=fontfile='${font}':text='Native action delay ${Math.round(d.delay*1000)} ms':x=64:y=50:fontsize=15:fontcolor=0xffcb79:enable='gte(t,${d.filmTime})*lt(t,${d.filmTime+2})'`);
 const title=`drawtext=fontfile='${font}':text='${b.label}':x=64:y=21:fontsize=28:fontcolor=white`;
 const captions=chapterNames.map((name,i)=>`drawtext=fontfile='${font}':text='${nativeCaption(b,i)}':x=w-tw-64:y=23:fontsize=24:fontcolor=0x9dada9:enable='gte(t,${scenario.chapters[i].startSeconds})*lt(t,${scenario.chapters[i].startSeconds+scenario.chapters[i].durationSeconds})'`).join(',');
 await encode(['-v','error','-n','-i',clean,'-vf',`scale=1792:1008,pad=1920:1080:64:72:color=0x111a1b,${title},${captions}${delayAnnotations.length?','+delayAnnotations.join(','):''}`,'-an','-frames:v','2100','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart'],path.join(deliver,`${b.folder}.mp4`),{source:hash(await readFile(clean))});
 }
 if(builds.length===3){const filters=masters.map((_,i)=>`[${i}:v]scale=1280:720[v${i}]`).join(';')+';[v0][v1][v2]hstack=inputs=3,pad=3840:840:0:120:color=0x111a1b,'+builds.map((b,i)=>`drawtext=fontfile='${font}':text='${b.label}':x=${i*1280+36}:y=24:fontsize=34:fontcolor=white`).join(',')+','+builds.flatMap((b,column)=>chapterNames.map((name,i)=>`drawtext=fontfile='${font}':text='${nativeCaption(b,i)}':x=${column*1280+36}:y=78:fontsize=24:fontcolor=0x9dada9:enable='gte(t,${scenario.chapters[i].startSeconds})*lt(t,${scenario.chapters[i].startSeconds+scenario.chapters[i].durationSeconds})'`)).concat(delays.map(d=>`drawtext=fontfile='${font}':text='Native action delay ${Math.round(d.delay*1000)} ms':x=${builds.findIndex(b=>b.id===d.build)*1280+600}:y=34:fontsize=21:fontcolor=0xffcb79:enable='gte(t,${d.filmTime})*lt(t,${d.filmTime+2})'`)).join(',');await encode(['-v','error','-n',...masters.flatMap(p=>['-i',p]),'-filter_complex',filters,'-an','-frames:v','2100','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart'],path.join(deliver,'demolition-comparison.mp4'),{sources:await Promise.all(masters.map(async f=>hash(await readFile(f))))});}
 await save(path.join(deliver,'selection.json'),selection);await save(path.join(deliver,'action-delay-annotations.json'),delays);console.log(`Assembled ${kind} films: ${deliver}`);
}
