import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fingerprint} from './verify.mjs';
import {validateActions} from './control-checks.mjs';
import {root,demo,builds,json,save,launch,capture,run,hash} from './core.mjs';
const args=process.argv.slice(2),command=args.shift()??'help';const arg=(k,d)=>args.includes(`--${k}`)?args[args.indexOf(`--${k}`)+1]:d;
const prompt=arg('prompt','demolition-playground'),runId=arg('run','demolition-demo-v1');if(!/^[a-z0-9-]+$/.test(prompt)||!/^[a-z0-9-]+$/.test(runId))throw Error('Invalid selector');
const out=path.resolve(arg('output',path.join(root,'.demo-work',runId)));await mkdir(out,{recursive:true});
const scenario=await json(path.join(root,`prompts/${prompt}/demo/scenario.json`));const selected=builds.filter(b=>!arg('build')||b.id===arg('build'));if(!selected.length)throw Error('Unknown build selector');
async function calibrate(){try{await readFile(path.join(out,'freeze.json'));throw Error('Calibration is frozen; use a new run ID');}catch(e){if(e.code!=='ENOENT')throw e;}for(const b of selected){const session=await launch(b,scenario,out,'calibrate');try{const nativeDir=path.join(out,'calibration',b.id);await mkdir(nativeDir,{recursive:true});await save(path.join(nativeDir,'original-camera.json'),await session.page.evaluate(()=>window.__comparison.nativeView()));await session.page.screenshot({path:path.join(nativeDir,'original-camera.png')});const inspection=await session.page.evaluate(()=>window.__comparison.inspect());const measuredEnvelope=await json(path.resolve(arg('motion',path.join(root,`prompts/${prompt}/demo/calibration`)),`${b.id}.json`));const calibration=await session.page.evaluate(e=>window.__comparison.calibrate(e),measuredEnvelope);const dir=path.join(out,'calibration',b.id);await mkdir(dir,{recursive:true});await save(path.join(dir,'scene.json'),inspection);await save(path.join(dir,'camera.json'),calibration);for(const shot of ['overview','ball']){await save(path.join(dir,`${shot}.json`),await session.page.evaluate(s=>window.__comparison.view(s),shot));await session.page.screenshot({path:path.join(dir,`${shot}.png`)});}await session.page.evaluate(()=>window.__comparison.view('overview'));const charges=await session.page.evaluate(()=>window.__comparison.checkCharges());await session.page.waitForTimeout(200);await save(path.join(dir,'charges.json'),charges);await session.page.screenshot({path:path.join(dir,'charges.png')});await save(path.join(dir,'result.json'),{passed:true,errors:session.errors});console.log(`Calibrated ${b.label}`);}finally{await session.close();}}if(selected.length===3){const {default:sheet}=await import('./contact-sheet.mjs');await sheet({out,builds:selected});}}
async function record(kind='official'){if(kind==='official'){const {freeze}=await import('./verify.mjs');await freeze(scenario,out);}for(const b of selected){const calibration=await json(path.join(out,'calibration',b.id,'camera.json'));for(const original of scenario.chapters){if(arg('chapter')&&original.id!==arg('chapter'))continue;const chapter=structuredClone(original);if(b.id!=='site'&&chapter.id==='charges-rewind'){chapter.events.push(...['bank','warehouse','glass-tower'].map((target,i)=>({at:4+i,action:'charge.place',target})));chapter.events.sort((a,b)=>a.at-b.at);}const dir=path.join(out,kind,b.id,chapter.id,`take-${Date.now()}`);const session=await launch(b,scenario,out,`${kind}-${chapter.id}`);try{await save(path.join(dir,'inputs.json'),await fingerprint(scenario,out));await save(path.join(dir,'source.json'),await json(path.join(out,'work',b.id,'source.json')));const result=await capture(session,dir,{chapter,calibration});try{await save(path.join(dir,'controls.json'),validateActions(b,chapter,result.receipts));}catch(error){await save(path.join(dir,'controls.json'),{passed:false,error:error.message});throw error;}console.log(`Captured ${kind} ${b.id}/${chapter.id}: ${result.frames.length} frames`);}finally{await session.close();}}}}
try{if(command==='calibrate')await calibrate();else if(command==='record')await record(arg('kind','official'));else if(command==='help')console.log('npm run demo -- calibrate|pilot|record|assemble|verify|publish|all [--prompt demolition-playground] [--run demolition-demo-v1] [--build site|sol|astra]');else{const mod=await import(`./${command}.mjs`);await mod.default({root,demo,builds:selected,scenario,out,runId,calibrate,record,args});}}catch(e){await save(path.join(out,`failure-${Date.now()}.json`),{command,message:e.message,stack:e.stack});console.error(e);process.exitCode=1;}
