import path from 'node:path';
import {cmd,json,save} from './core.mjs';
export function frameSchedule(frames,start,duration,fps=30){const ordered=frames.map((f,sourceIndex)=>({...f,sourceIndex})).sort((a,b)=>a.timestamp-b.timestamp||a.sourceIndex-b.sourceIndex);const rows=[];let i=0;for(let n=0;n<Math.round(duration*fps);n++){const t=start+n/fps;while(i+1<ordered.length&&ordered[i+1].timestamp<=t)i++;rows.push({outputFrame:n,time:n/fps,sourceIndex:ordered[i].sourceIndex,sourceTimestamp:ordered[i].timestamp,holdSeconds:t-ordered[i].timestamp});}return rows;}
function color(dir,f){const v=cmd('ffmpeg',['-v','error','-i',path.join(dir,'frames',f.file),'-vf','crop=8:8:16:16,scale=1:1','-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{encoding:null});const [r,g,b]=v;return r>200&&g<60&&b>200?'pre':r<60&&g>200&&b>200?'end':'live';}
export async function inspectTiming(dir,duration){const capture=await json(path.join(dir,'capture.json')),receipt=await json(path.join(dir,'receipts.json')),f=capture.frames.map((x,arrivalIndex)=>({...x,arrivalIndex})).sort((a,b)=>a.timestamp-b.timestamp||a.arrivalIndex-b.arrivalIndex);const marks=[];
 for(const phase of ['live','end']){const m=receipt.markers.find(m=>m.phase===phase);if(!m)throw Error(`Missing ${phase} marker`);const at=m.epoch/1000;const around=f.map((x,i)=>({...x,index:i})).filter(x=>Math.abs(x.timestamp-at)<.6);const samples=around.map(x=>({...x,color:color(dir,x)}));const first=samples.find(x=>x.color===phase);if(!first||first.index===0)throw Error(`Visible ${phase} synchronization transition not found`);const previous=f[first.index-1];marks.push({phase,pageEpoch:at,previousTimestamp:previous.timestamp,firstTimestamp:first.timestamp,intervalSeconds:first.timestamp-previous.timestamp,offsetLow:previous.timestamp-at,offsetHigh:first.timestamp-at,samples:samples.map(s=>({index:s.index,timestamp:s.timestamp,color:s.color}))});}
 const offsetLow=Math.max(...marks.map(m=>m.offsetLow)),offsetHigh=Math.min(...marks.map(m=>m.offsetHigh));if(offsetLow>offsetHigh+1/30)throw Error('Synchronization markers disagree by more than one output frame');const live=marks.find(m=>m.phase==='live'),finish=marks.find(m=>m.phase==='end');const offset=live.offsetHigh,start=live.firstTimestamp;const endpointDurationError=finish.firstTimestamp-start-duration;const gaps=[];
 for(let i=1;i<f.length;i++)if(f[i].timestamp-f[i-1].timestamp>.1){const a=f[i-1].timestamp-offset,b=f[i].timestamp-offset;const native=receipt.frames.filter(r=>r.epoch/1000>=a-.02&&r.epoch/1000<=b+.02);gaps.push({from:f[i-1].timestamp,to:f[i].timestamp,seconds:b-a,nativeSamples:native.length,maxRawDeltaMs:Math.max(0,...native.map(r=>r.rawDelta??0)),classification:native.some(r=>r.rawDelta>75)?'native-animation-stall':'unexplained'});}
 const uncertainty=Math.max(...marks.map(m=>Math.max(Math.abs(m.offsetLow-offset),Math.abs(m.offsetHigh-offset))));const result={start,duration,clockOffsetSeconds:offset,logicalStartPageEpoch:live.pageEpoch,endpointDurationError,uncertaintySeconds:uncertainty,markers:marks,gaps,actionDelays:receipt.events.filter(e=>e.planned!==null&&e.actual-e.planned>.1).map(e=>({action:e.action,planned:e.planned,actual:e.actual,delay:e.actual-e.planned})),passed:uncertainty<=1/30&&Math.abs(endpointDurationError)<=1/30&&!gaps.some(g=>g.classification==='unexplained')};await save(path.join(dir,'timing.json'),result);await save(path.join(dir,'encoded-frame-map.json'),frameSchedule(f,start,duration));return result;}
