import path from 'node:path';
import {readFile,readdir} from 'node:fs/promises';
import {root,demo,cmd,json,save,hash,run} from './core.mjs';
import {inspectFreshness,freezeFreshness,assertFreshnessFreeze} from './freshness.mjs';
export async function preservation(scenario){const prefix=`prompts/${scenario.promptId}/builds/`;const files=cmd('git',['ls-tree','-r','--name-only',scenario.sourceCommit,'--',prefix]).trim().split('\n');const rows=[];for(const file of files){const before=cmd('git',['show',`${scenario.sourceCommit}:${file}`],{encoding:null});const after=await readFile(path.join(root,file));rows.push({file,sha256:hash(after),expectedSha256:hash(before),unchanged:hash(after)===hash(before)});}return {passed:rows.every(r=>r.unchanged),files:rows};}
export function probe(file){return JSON.parse(cmd('ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',file]));}
export async function fingerprint(scenario,out){const files=['showcase/demo/browser-runtime.js','showcase/demo/core.mjs','showcase/demo/timing.mjs','showcase/demo/run.mjs','showcase/demo/control-checks.mjs','showcase/attempts.json',`prompts/${scenario.promptId}/demo/scenario.json`,...['site','sol','astra'].flatMap(id=>[`showcase/demo/patches/${id}.json`,`prompts/${scenario.promptId}/demo/calibration/${id}.json`,`prompts/${scenario.promptId}/demo/calibration/${id}-native-motion.json`])];const inputs={};for(const f of files)inputs[f]=hash(await readFile(path.join(root,f)));for(const id of ['site','sol','astra'])inputs[`calibration/${id}`]=hash(await readFile(path.join(out,'calibration',id,'camera.json')));return {inputs,sha256:hash(JSON.stringify(inputs))};}
export async function freeze(scenario,out){const current=await fingerprint(scenario,out);await freezeFreshness(out,current.sha256);const control=await json(path.join(out,'pilot','control-result.json'));if(!control.passed)throw Error('Disk pilot not passed');const review=await json(path.join(out,'calibration','independent-review.json'));if(review.status!=='pass'||review.fingerprint!==current.sha256)throw Error('Independent calibration review missing or stale');let previous;try{previous=await json(path.join(out,'freeze.json'));}catch{}if(previous&&previous.sha256!==current.sha256)throw Error('Frozen recording inputs changed; use a new run');if(!previous){const {builds}=await import('./core.mjs');const {chooseTake}=await import('./assemble.mjs');for(const b of builds)for(const chapter of scenario.chapters){const take=await chooseTake(out,'rehearsal',b,chapter);const manifest=await json(path.join(take.dir,'inputs.json'));if(manifest.sha256!==current.sha256)throw Error('Rehearsal inputs are stale');}}if(!previous)await save(path.join(out,'freeze.json'),{...current,at:new Date().toISOString(),settings:{jpegQuality:95,width:1920,height:1080,deviceScaleFactor:1,fps:30,crf:18}});return current;}
export default async function verify({scenario,out,builds}){await assertFreshnessFreeze(out);await run('npm',['run','test:demo']);const original=await preservation(scenario);await save(path.join(out,'preservation.json'),original);if(!original.passed)throw Error('Original build preservation failed');
 const selection=await json(path.join(out,'delivery','selection.json')),freshness=[];
 for(const b of builds)for(const chapter of scenario.chapters){const entries=selection.filter(s=>s.build===b.id&&s.chapter===chapter.id);if(entries.length!==1)throw Error('Missing or duplicate selected chapter');const dir=path.join(out,entries[0].take),capture=await json(path.join(dir,'capture.json')),timing=await json(path.join(dir,'timing.json'));freshness.push({build:b.id,chapter:chapter.id,take:entries[0].take,...inspectFreshness(capture,timing)});}
 await save(path.join(out,'output-freshness-verification.json'),{status:freshness.every(f=>f.status==='pass')?'pass':'inconclusive',chapters:freshness});
 if(freshness.some(f=>f.status!=='pass'))throw Error('Output-frame freshness is inconclusive; independent review required');
 const dir=path.join(out,'delivery'),films=[];for(const [name,width,height] of [...builds.map(b=>[`${b.folder}.mp4`,1920,1080]),['demolition-comparison.mp4',3840,840]]){const file=path.join(dir,name),meta=probe(file),v=meta.streams.find(s=>s.codec_type==='video');const bytes=await readFile(file);let atom=0,moov=-1,mdat=-1;while(atom+8<=bytes.length){let size=bytes.readUInt32BE(atom);const type=bytes.toString('ascii',atom+4,atom+8);if(size===1)size=Number(bytes.readBigUInt64BE(atom+8));if(type==='moov')moov=atom;if(type==='mdat')mdat=atom;if(!size)break;atom+=size;}const result={fastStart:moov>=0&&mdat>=0&&moov<mdat,file:name,sha256:hash(await readFile(file)),width:v.width,height:v.height,frames:Number(v.nb_read_frames),duration:Number(v.duration),codec:v.codec_name,pixelFormat:v.pix_fmt,fps:v.avg_frame_rate,audio:meta.streams.some(s=>s.codec_type==='audio')};result.passed=result.fastStart&&result.width===width&&result.height===height&&result.frames===2100&&result.duration===70&&result.codec==='h264'&&result.pixelFormat==='yuv420p'&&result.fps==='30/1'&&!result.audio;films.push(result);}const result={status:films.every(f=>f.passed)?'pass':'fail',scope:'automated-preservation-and-media-properties',films,independentReviewRequired:true};await save(path.join(out,'technical-verification.json'),result);if(result.status!=='pass')throw Error('Media verification failed');console.log('Technical media verification passed; fresh independent recording/viewer review is required before publish.');}
