import path from 'node:path';
import assert from 'node:assert/strict';
import {mkdir,copyFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {root,demo,builds,cmd,save,sleep} from './core.mjs';
export default async function viewerChecks({out}){
 const dir=path.join(out,'viewer-check'),session=`demo-viewer-check-${Date.now()}`;await mkdir(dir,{recursive:true});await copyFile(path.join(demo,'viewer.html'),path.join(dir,'index.html'));for(const b of builds)await copyFile(path.join(out,'delivery',b.folder+'.mp4'),path.join(dir,b.folder+'.mp4'));
 const ab=(...a)=>{const r=JSON.parse(cmd('agent-browser',['--session',session,'--json',...a]));if(!r.success)throw Error(JSON.stringify(r));return r.data;};const evaluate=code=>{const r=ab('eval',code);return r.result??r;};const state=()=>evaluate('window.comparisonViewer.state()');
 const result={startedAt:new Date().toISOString(),checks:[]};let server;
 async function until(check,timeout=15000){const start=Date.now();while(Date.now()-start<timeout){const value=check();if(value)return value;await sleep(100);}throw Error('Viewer condition timed out');}
 function check(name,test,evidence){assert.ok(test,name);result.checks.push({name,passed:true,evidence});}
 try{
  ab('open','file://'+path.join(dir,'index.html'));ab('set','viewport','1920','1080','1');ab('snapshot','-i');await until(()=>state().players.every(v=>v.ready>=3));
  ab('click','#play');await sleep(1800);let s=state();check('Offline play starts all films at normal speed',s.playing&&s.players.every(v=>!v.paused&&v.rate===1),s);
  ab('click','#play');s=state();check('Pause stops the shared timeline and all films',!s.playing&&s.players.every(v=>v.paused),s);
  ab('click','[data-time="26"]');await until(()=>!state().busy);s=state();check('Chapter navigation seeks all films to 26 seconds',s.players.every(v=>Math.abs(v.time-26)<.02),s);
  evaluate("document.querySelector('#seek').value=42.5;document.querySelector('#seek').dispatchEvent(new Event('input',{bubbles:true}))");await until(()=>!state().busy);s=state();check('Shared seeking reaches arbitrary time',s.players.every(v=>Math.abs(v.time-42.5)<.02),s);
  ab('click','[data-focus="1"]');const focus=evaluate("({selected:comparisonViewer.state().focus,visible:[...document.querySelectorAll('figure')].map(f=>getComputedStyle(f).display!=='none')})");check('Focus shows the selected build',focus.selected===1&&focus.visible.filter(Boolean).length===1&&focus.visible[1],focus);
  ab('click','#all');ab('screenshot',path.join(dir,'desktop.png'));ab('set','viewport','390','844','1');ab('select','#pick','2');const mobile=evaluate("({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,selected:comparisonViewer.state().focus,visible:[...document.querySelectorAll('figure')].map(f=>getComputedStyle(f).display!=='none')})");check('Narrow layout fits and selects one build',mobile.width===mobile.scrollWidth&&mobile.selected===2&&mobile.visible.filter(Boolean).length===1,mobile);ab('screenshot',path.join(dir,'mobile.png'));
  ab('set','viewport','1920','1080','1');ab('click','[data-time="8"]');await until(()=>!state().busy);ab('click','#play');await sleep(500);const corrections=state().driftCorrections;evaluate('document.querySelectorAll("video")[1].pause()');await until(()=>state().driftCorrections>corrections&&!state().busy);s=state();check('Drift over 80 ms is corrected by seeking with rates fixed at 1',s.players.every(v=>Math.abs(v.time-s.time)<.08&&v.rate===1),s);ab('click','#play');
  // Locate byte position at ~3 seconds, then withhold real Sol response bytes there.
  const packet=JSON.parse(cmd('ffprobe',['-v','error','-select_streams','v:0','-show_packets','-show_entries','packet=pts_time,pos,size','-of','json',path.join(dir,'gpt-5.6-sol-ultra.mp4')])).packets.find(p=>Number(p.pts_time)>=3.2);const limit=Number(packet.pos)+Number(packet.size);const port=4339;try{await fetch(`http://127.0.0.1:${port}`,{signal:AbortSignal.timeout(500)});throw Error('Viewer test port is occupied');}catch(e){if(e.message.includes('occupied'))throw e;}
  server=spawn(process.execPath,[path.join(demo,'viewer-fixture-server.mjs'),dir,String(port),String(limit)],{stdio:'ignore'});await sleep(400);ab('open',`http://127.0.0.1:${port}/index.html?metadata=1`);ab('click','[data-time=\"26\"]');const pending=state();check('Early seek waits for all metadata',pending.busy&&pending.players.every(v=>v.ready===0),pending);await fetch(`http://127.0.0.1:${port}/release`);await until(()=>!state().busy&&state().players.every(v=>v.ready>=3));s=state();check('Early seek is honored after metadata arrives',s.players.every(v=>Math.abs(v.time-26)<.02&&v.paused),s);await fetch(`http://127.0.0.1:${port}/reset`);ab('open',`http://127.0.0.1:${port}/index.html`);evaluate("document.querySelectorAll('video')[1].src='gpt-5.6-sol-ultra.mp4?buffer=1';window.bufferEvents=[];document.querySelectorAll('video').forEach((v,i)=>v.addEventListener('waiting',()=>bufferEvents.push({player:i,at:performance.now(),state:comparisonViewer.state()})))");await until(()=>state().players.every(v=>v.ready>=3));ab('click','#play');await until(()=>{const s=state();return s.desired&&!s.playing&&s.time>1;},20000);const stalled=state();await sleep(1000);const held=state();check('Real byte starvation pauses all players and freezes time',stalled.players.every(v=>v.paused)&&held.players.every(v=>v.paused)&&Math.abs(held.time-stalled.time)<.02,{limit,stalled,held,events:evaluate('bufferEvents')});await fetch(`http://127.0.0.1:${port}/release`);await until(()=>state().playing);await sleep(1000);s=state();check('Playback resumes together after buffering',s.playing&&s.players.every(v=>!v.paused&&v.rate===1&&Math.abs(v.time-s.time)<.08),s);
  result.status='pass';
 }catch(e){result.status='fail';result.error=e.message;throw e;}finally{try{ab('close');}catch{}if(server)server.kill('SIGTERM');await save(path.join(dir,`checks-${result.startedAt.replaceAll(':','-')}.json`),result);await save(path.join(dir,'checks.json'),result);}
 console.log('Viewer offline controls, layouts, drift and real buffering checks passed.');
}
