attachComparison({THREE,camera,scene,controls,renderer,
 describe(){scene.updateMatrixWorld(true);const bound=b=>{const x=new THREE.Box3();for(const f of b.floors)x.expandByObject(f.group);return {min:x.min.toArray(),max:x.max.toArray()};};const all=new THREE.Box3();for(const b of city.buildings){const x=bound(b);all.union(new THREE.Box3(new THREE.Vector3(...x.min),new THREE.Vector3(...x.max)));}const cb=new THREE.Box3().setFromObject(crane.root).expandByObject(crane.cable).expandByObject(crane.ball);all.union(cb);const b=city.buildings[0];return {frontAzimuthDegrees:0,front:[0,0,1],right:[1,0,0],facadeCenters:Object.fromEntries(Object.entries({bank:0,warehouse:4,'glass-tower':3}).map(([key,id])=>{const b=city.buildings[id];return [key,[b.x,2,b.z+b.depth/2]];})),columnObservations:city.buildings.flatMap(b=>b.floors.flatMap(f=>f.columns.map((p,i)=>({key:`${b.id}/${f.index}/${i}`,building:b.id,floor:f.index,local:[p.x,p.z]})))),fitBounds:[...city.buildings.map(bound),{min:cb.min.toArray(),max:cb.max.toArray()}],bounds:{min:all.min.toArray(),max:all.max.toArray()},craneBounds:{min:cb.min.toArray(),max:cb.max.toArray()},bankBounds:bound(b),bankPoint:[b.x,5,b.z+b.depth/2]};},
 swingEnvelope(p){const target=new THREE.Vector3(...p.bankPoint),goalYaw=Math.atan2(target.z-crane.base.z,target.x-crane.base.x),delta=Math.atan2(Math.sin(goalYaw-crane.yaw),Math.cos(goalYaw-crane.yaw)),reach=THREE.MathUtils.clamp(Math.hypot(target.x-crane.base.x,target.z-crane.base.z)+2,14,51),length=Math.max(crane.length,THREE.MathUtils.clamp(42-THREE.MathUtils.clamp(target.y,3,32),9,39)),bounds=new THREE.Box3();for(let i=0;i<=32;i++){const u=i/32,yaw=crane.yaw+delta*u,r=crane.reach+(reach-crane.reach)*u,anchor=new THREE.Vector3(crane.base.x+Math.cos(yaw)*r,42,crane.base.z+Math.sin(yaw)*r);bounds.expandByPoint(anchor.clone().addScalar(length+1.8));bounds.expandByPoint(anchor.clone().addScalar(-length-1.8));}return {min:bounds.min.toArray(),max:bounds.max.toArray(),method:'initial/prepared tether spheres along the native shortest yaw arc, including ball radius'};},
 supports(key){const id={bank:0,warehouse:4,'glass-tower':3}[key],b=city.buildings[id],f=b.floors[0];return [{key:`${id}/0/facade`,id,floor:0,kind:'native-ground-floor-facade',bounds:{min:[b.x-b.width/2,f.y+.35,b.z-b.depth/2],max:[b.x+b.width/2,f.y+f.height-.35,b.z+b.depth/2]}}];},
 hit(screen){return pick({clientX:screen.x,clientY:screen.y});},
 matches(s,h){return h.building.id===s.id&&h.floor.index===0;},
 hitIdentity(h){return {building:h.building.id,floor:h.floor.index,kind:'native-facade',actualHit:h.point.toArray()};},
 renderSettings(){return {preset:simulation.quality,pixelRatio:renderer.getPixelRatio(),shadowMapSize:sun.shadow.mapSize.toArray(),shadowsEnabled:renderer.shadowMap.enabled};},
 motion(){return {ball:crane.ballPosition.toArray(),anchor:crane.anchor.toArray()};},
 observe(){return {quality:simulation.quality,time:simulation.time,cursor,slow:slow||spaceSlow,mode:rewinding?'rewind':paused?'paused':'live',tonnage:simulation.stats.tonnage,charges:simulation.charges.map(c=>({...c,building:simulation.floors[c.floor].building.id})),crane:crane.capture()};},
 chargePoints(){return simulation.charges.map(c=>simulation.floors[c.floor].floor.group.localToWorld(new THREE.Vector3(c.x,c.y,c.z)));},
 action(action,cal,extra){
 if(action==='charges.prepareSet')$('charge-tool').click();
 if(action==='charge.detonate')$('detonate').click();
 if(action==='slow.set')setSlow(extra.enabled);
 if(action==='rewind.start')$('rewind').click();
 if(action==='charge.place'||action==='ball.swingOnce'){const target=action==='charge.place'?cal.targets[extra.target].point:cal.bankPoint;const p=new THREE.Vector3(...target).project(window.__comparison.camera);const event={clientX:(p.x+1)*innerWidth/2,clientY:(1-p.y)*innerHeight/2,button:0};const hit=pick(event);if(!hit)throw Error('Native pointer missed target');comparisonDown(event);comparisonUp(event);return {point:hit.point.toArray(),building:hit.building.id,floor:hit.floor.index};}
 }
});
