attachComparison({THREE,camera,scene,controls,renderer,automaticCharges:true,
 describe(){scene.updateMatrixWorld(true);const bound=b=>{const x=new THREE.Box3();for(const m of b.members)x.expandByObject(m.mesh);if(b.waterTank)x.expandByObject(b.waterTank);return {min:x.min.toArray(),max:x.max.toArray()};};const all=new THREE.Box3();for(const b of buildings){const x=bound(b);all.union(new THREE.Box3(new THREE.Vector3(...x.min),new THREE.Vector3(...x.max)));}const cb=new THREE.Box3().setFromObject(crane.base).expandByObject(crane.arm).expandByObject(crane.cable).expandByObject(crane.ball);all.union(cb);const bank=buildings.find(b=>b.id==='bank');return {frontAzimuthDegrees:180,front:[0,0,-1],right:[-1,0,0],fitBounds:[...buildings.map(bound),{min:cb.min.toArray(),max:cb.max.toArray()}],bounds:{min:all.min.toArray(),max:all.max.toArray()},craneBounds:{min:cb.min.toArray(),max:cb.max.toArray()},bankBounds:bound(bank),bankPoint:[bank.position.x,5,bank.position.z-bank.size.z/2]};},
 swingEnvelope(p){const target=new THREE.Vector3(...p.bankPoint),d=target.clone().sub(crane.pivot),yaw=THREE.MathUtils.degToRad(Math.round(clamp(THREE.MathUtils.radToDeg(Math.atan2(d.z,d.x)),-60,60))),line=Math.round(clamp(crane.pivot.distanceTo(target)*.42,10,24));const bounds=new THREE.Box3();for(const angle of [-1.25,0,1.25])for(const cable of [crane.cableLength,line])for(const theta of [crane.yaw,yaw]){bounds.expandByPoint(crane.pivot.clone().add(new THREE.Vector3(Math.cos(theta)*Math.sin(angle)*cable,-Math.cos(angle)*cable,Math.sin(theta)*Math.sin(angle)*cable)));}bounds.expandByScalar(1.6);return {min:bounds.min.toArray(),max:bounds.max.toArray(),method:'native swing-angle clamp and initial/prepared cable lengths, including ball radius and lateral sway'};},
 renderSettings(){return {preset:state.quality,pixelRatio:renderer.getPixelRatio(),shadowMapSize:sun.shadow.mapSize.toArray(),shadowsEnabled:renderer.shadowMap.enabled,renderMode:renderBudget.mode,targetPixelRatio:renderBudget.targetPixelRatio,shadowUpdateStride:renderBudget.shadowStride};},
 motion(){return {ball:crane.ballPosition.toArray(),anchor:crane.pivot.toArray()};},
 observe(){return {quality:state.quality,time:state.simTime,slow:state.timeScale,rewinding:state.rewinding,tonnage:state.score.tonnage,charges:charges.map(c=>({id:c.id,building:c.member.building.id,member:c.member.id,point:c.mesh.position.toArray(),detonated:c.detonated})),crane:{yaw:crane.yaw,cable:crane.cableLength,position:crane.ballPosition.toArray()}};},
 chargePoints(){return charges.map(c=>c.mesh.position.clone());},
 action(action,cal,extra){
 if(action==='ball.prepare'){const target=new THREE.Vector3(...cal.bankPoint);const d=target.clone().sub(crane.pivot);ui.craneYaw.value=String(Math.round(clamp(THREE.MathUtils.radToDeg(Math.atan2(d.z,d.x)),-60,60)));ui.cableLength.value=String(Math.round(clamp(crane.pivot.distanceTo(target)*.42,10,24)));return {yaw:ui.craneYaw.value,cable:ui.cableLength.value};}
 if(action==='ball.swingOnce')document.querySelector('[data-action="swing"]').click();
 if(action==='charges.prepareSet')document.querySelector('[data-tool="charge"]').click();
 if(action==='charge.detonate')document.querySelector('[data-action="detonate"]').click();
 if(action==='slow.set')window.__comparisonSlow[extra.enabled?'on':'off']();
 if(action==='rewind.start')document.querySelector('[data-action="rewind"]').click();
 }
});
